---
- name: Kubeadm | Master | Ensure kubeadm required directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 'u+rw,g+r,o+r'
  with_items:
    - "{{ kubeadm_exec_dir }}"
    - "{{ kubeadm_sync_dirs }}"

- name: Kubeadm | Get Kubeadm binary
  ansible.builtin.get_url:
    url: "{{ kubernetes_binaries_url }}/kubeadm"
    mode: 0755
    dest: "{{ bin_dir }}/kubeadm"
    force: true

- name: Kubeadm | Master | Copy kubeadm init config file
  ansible.builtin.template:
    src: kubeadm-config.yaml.j2
    dest: "{{ kubeadm_exec_dir }}/kubeadm-config.yaml"
    mode: 'u+rw,g+r,o+r'
  register: kubeadm_config

- ansible.builtin.include_tasks: phase_certs.yml
  when: kubeadm_config.changed or kubeadm_force_init

- ansible.builtin.include_tasks: phase_config.yml
  when: kubeadm_config.changed or kubeadm_force_init

- ansible.builtin.include_tasks: phase_etcd.yml
  when: kubeadm_config.changed or kubeadm_force_init

- ansible.builtin.include_tasks: phase_controlplane.yml
  when: kubeadm_config.changed or kubeadm_force_init

- ansible.builtin.include_tasks: phase_tokens.yml
  when: kubeadm_config.changed or kubeadm_force_init

- ansible.builtin.include_tasks: phase_config_upload.yml
  when: kubeadm_config.changed or kubeadm_force_init

- ansible.builtin.include_tasks: phase_mark_master.yml
  when: kubeadm_config.changed or kubeadm_force_init

- ansible.builtin.include_tasks: phase_kubelet_finalize.yml
  when: kubeadm_config.changed or kubeadm_force_init

- ansible.builtin.include_tasks: phase_addons.yml
  when: kubeadm_config.changed or kubeadm_force_init

- ansible.builtin.include_tasks: phase_certs_renew.yml
