---
- ansible.builtin.include_tasks: controlplane_check.yml

- ansible.builtin.include_tasks: etcd_cleanup.yml
  when:
    - kubernetes_control_plane_local.rc == 2
    - kubernetes_control_plane_delegated is success
    - groups['master']|length > 1

- ansible.builtin.include_tasks: kubeadm.yml

- ansible.builtin.include_tasks: kubeconfig.yml
