---
- name: Kubeadm | Master | Kubelet and kubeconfig phase
  ansible.builtin.shell: |
    {{ bin_dir }}/kubeadm init phase kubeconfig all --config kubeadm-config.yaml
    {{ bin_dir }}/kubeadm init phase kubelet-start  --config kubeadm-config.yaml
  args:
    chdir: "{{ kubeadm_exec_dir }}"
  notify: restart kubelet

- name: Kubeadm | Master | Restart kubelet
  ansible.builtin.meta: flush_handlers
