---
- name: Kubeadm | Master | Kubelet finalize
  ansible.builtin.shell: |
    {{ bin_dir }}/kubeadm init phase kubelet-finalize all  --config kubeadm-config.yaml
  args:
    chdir: "{{ kubeadm_exec_dir }}"
