---
- name: Kubeadm | Master | Control plane phase
  ansible.builtin.shell: |
    {{ bin_dir }}/kubeadm init phase control-plane all --config kubeadm-config.yaml
  args:
    chdir: "{{ kubeadm_exec_dir }}"
