---
- name: Kubeadm | Master | Mark master phase
  ansible.builtin.shell: |
    {{ bin_dir }}/kubeadm init phase mark-control-plane
  args:
    chdir: "{{ kubeadm_exec_dir }}"
  retries: 10
  delay: 5
  when: kubeadm_mark_control_plane
