---
- name: Kubeadm | Node | Register nodes
  ansible.builtin.shell: |
    {{ bin_dir }}/kubectl get nodes -o=custom-columns=NAME:.metadata.name --no-headers
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  args:
    executable: /bin/bash
    chdir: "{{ kubeadm_exec_dir }}"
  register: nodes
  run_once: true
  delegate_to: "{{ groups['master'] | random(seed=inventory_hostname) }}"
  changed_when: false
